### ISSUE TITLE
troubles ifpass starting with "--"

### ISSUE THREAD

**Issue by HaraldSchlager** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#1]
hi brendan, I tried to login a generated password from UCYBCRYP.exe

java -jar TASKS_Operations.jar -L USER1 -W --100458AAAAAAAAC08Y12B7XXX0XE6X2X
or
java -jar TASKS_Operations.jar -L USER1 -W '--100458AAAAAAAAC08Y12B7XXX0XE6X2X'
 
-- Error: Logon error: Access denied

AE_IP_ADR = localhost
AE_PRIMARY_PORT = 99999
AE_CLIENT = 424
AE_LOGIN = x
AE_DEPT = UC
AE_PASSWORD = x

The idea was that I don't want to put the credentials in the connection.config.

If I use "my" jar for connection I am able to login with this credentials or if I use the unencrypted password with your jar's it is also working.

any idea ?

thank's,
harald

**Comment by brendanSapience** [comment]
Hi Harald,

The password can be encrypted and stored (in encrypted form) in the connection.config file, however, you are correct, it cant currently be passed to option -W in encrypted form..

let me fix that :) 

i will get back to you when done.

**Comment by brendanSapience** [comment]
Harald,

**The bad news**: you wont be able to use your password encrypted by UCYBCRYP.exe in the -W option.

**The good news**: you can encrypt your password using the newly delivered "Encrypt_Utils.jar" and use its output in the -W option.

**Ex:** 
_java -jar Encrypt_Utils.jar M3P@ssw0rd
Encrypted Password:--10DFF1D9F7124004DC6975175875258363_

**then:**
_java -jar TASKS_Operations.jar -W --10DFF1D9F7124004DC6975175875258363_

and finally the reason why we cant use the same encryption / decryption mechanism as UCyBCRYP.exe: II simply dont have access to the encryption / decryption key :)

let me know if this works.

**Comment by HaraldSchlager** [comment]
Hi brendan, thank you for you efforts, I will try it.

**Comment by HaraldSchlager** [comment]
hi brendan, when I put single colons before myPassword it works. This is probably because I have
***$!*** signs in this password. 

Interesting for me is the reason why the encrypted pass with
the default  UCYBCRYP does not work with the -W option. I use it with e.g.

CreateSession aeSession = aeConn.login(424, "USER1","UC","--100458ABCDEXXXXXBBBCCYY...",'E');

this working for me via the standard API.

thanks,
harald

**Comment by HaraldSchlager** [comment]
hi brendan, in my test's I also got an error if i only pass "-h", "-help" does work. I think only in this new version.

java -jar TASKS_Operations.jar -h
Exception in thread "main" java.lang.StringIndexOutOfBoundsException
        at java.lang.String.substring(String.java:1247)
        at java.lang.String.subSequence(String.java:1808)
        at com.automic.std.ProcessStandardCLI.processStdCredentials(ProcessStandardCLI.java:142)
        at com.automic.specifics.GoRunCommand.main(GoRunCommand.java:45)

thank's,
Harald

**Comment by brendanSapience** [comment]
Very Interesting. I did not know that you could pass the password in encrypted form directly to the login method, but you are correct, it seems to work fine.

this means that the -W option as it was implemented before should have supported that as well.

let me revert back to supporting the standard encrypted password for -W and run some tests.

**Comment by HaraldSchlager** [comment]
thank you !

**Comment by brendanSapience** [comment]
Fixed! (and delivered).

here are the 3 possible syntax to pass an encrypted password with -W. You can use no quote around the password, single quotes or double quotes:

java -jar TASKS_Operations.jar -H AETestHost -W --1011A5E9D4669E1503D85868DBA3C7C4BA

java -jar TASKS_Operations.jar -H AETestHost -W '--1011A5E9D4669E1503D85868DBA3C7C4BA'

java -jar TASKS_Operations.jar -H AETestHost -W "--1011A5E9D4669E1503D85868DBA3C7C4BA"

I removed my "Encrypt_utils.jar" binary since as you pointed out the API natively supports passwords encrypted with UCYBCRYP.exe. No need for it!

let me know if it works.

**Comment by HaraldSchlager** [comment]
hi brendan, All 3 Versions are working :-) Thanks !

**Comment by HaraldSchlager** [comment]
Is there a possibiltiy to specify the "connection.config" e.g. java -jar TASKS_Operations.jar -P 1234569_FLUFFY_connection.config  -> uses instead the default connection.config the 1234569_FLUFFY_connection.config ?
Thanks, Harald

**Comment by brendanSapience** [comment]
good idea!

currently not possible.. i will implement this next week, im already super booked this week.

**Comment by HaraldSchlager** [comment]
great - thank you !

**Comment by brendanSapience** [comment]
Added!

new flag -F will allow you to specify a custom connection configuration file!

**Comment by HaraldSchlager** [comment]
hi brendan, -F  is working - thanks !
