### ISSUE TITLE
TASK_Operations -f_rangeendtime

### ISSUE THREAD

**Issue by HaraldSchlager** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#14]
hi brendan,
can I also use the TASK_Operations jar for "historical" queries ? I am trying the parameter f_rangeendtime but I get an error ( -f_rangeendtime <arg>     [OPTIONAL] ("[YYYYMMDD-hhmm,YYYYMMDD-hhmm]") - Time Range for End Time. ) :

eg40app01v:/app/automic/tools/binutils> java -jar TASKS_Operations.jar -H localhost -P 58200 -f_rangeendtime "[20161130-1000,20161130-1100]"
%% => Simulation Mode - Nothing will be updated. [ Hint: Run commit option to update objects (-commit) ] <= %%

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
        at com.automic.std.consistencyUtils.getUpdatePattern2(consistencyUtils.java:218)
        at com.automic.std.consistencyUtils.getUpdatePattern(consistencyUtils.java:201)

Thanks,
Harald

**Comment by brendanSapience** [comment]
Hi Harald,

the format should be:  -f_rangeendtime "['20161130-1000','20161130-1100']" (single quotes). There was no real control on the format in the binary, but i just added it and redelivered the binary. let me know if that works!

**Comment by brendanSapience** [comment]
#15 created and solved. New binary created for Statistics.

**Comment by HaraldSchlager** [comment]
hi brendan, thank's, the syntax with the single quote is working. Testing STATISTICS_List I get following error ( several executions ):

eg40app01v:/app/automic/tools/binutils> java -jar STATISTICS_List.jar -H localhost -P 58200 -f_rangeendtime "['20161030-1000','20161130-1100']"
%% => Simulation Mode - Nothing will be updated. [ Hint: Run commit option to update objects (-commit) ] <= %%

         -- Your selection results in too many statistics (count '77424'). Please define a more specific query (max. count '5000')
Exception in thread "main" java.lang.NullPointerException
        at com.automic.specifics.GoRunCommand.main(GoRunCommand.java:65)
eg40app01v:/app/automic/tools/binutils> java -jar STATISTICS_List.jar -H localhost -P 58200 -f_rangeendtime "['20161120-1000','20161130-1100']"
%% => Simulation Mode - Nothing will be updated. [ Hint: Run commit option to update objects (-commit) ] <= %%

         -- Your selection results in too many statistics (count '77425'). Please define a more specific query (max. count '5000')
Exception in thread "main" java.lang.NullPointerException
        at com.automic.specifics.GoRunCommand.main(GoRunCommand.java:65)
eg40app01v:/app/automic/tools/binutils> java -jar STATISTICS_List.jar -H localhost -P 58200 -f_rangeendtime "['20161125-1000','20161130-1100']"
%% => Simulation Mode - Nothing will be updated. [ Hint: Run commit option to update objects (-commit) ] <= %%

         -- Your selection results in too many statistics (count '77426'). Please define a more specific query (max. count '5000')
Exception in thread "main" java.lang.NullPointerException
        at com.automic.specifics.GoRunCommand.main(GoRunCommand.java:65)
eg40app01v:/app/automic/tools/binutils> java -jar STATISTICS_List.jar -H localhost -P 58200 -f_name ".TRANSPORT.MAIN.PLAN" -f_rangeendtime "['20161125-1000','20161130-1100']"
%% => Simulation Mode - Nothing will be updated. [ Hint: Run commit option to update objects (-commit) ] <= %%

         -- Your selection results in too many statistics (count '77428'). Please define a more specific query (max. count '5000')
Exception in thread "main" java.lang.NullPointerException
        at com.automic.specifics.GoRunCommand.main(GoRunCommand.java:65)

eg40app01v:/app/automic/tools/binutils> java -jar STATISTICS_List.jar -H localhost -P 58200 -f_name ".TRANSPORT.MAIN.PLAN" -f_rangestarttime "['20161125-1000','20161125-1000']" -f_rangeendtime "['20161125-1000','20161130-1100']"
%% => Simulation Mode - Nothing will be updated. [ Hint: Run commit option to update objects (-commit) ] <= %%

         -- Your selection results in too many statistics (count '77429'). Please define a more specific query (max. count '5000')
Exception in thread "main" java.lang.NullPointerException
        at com.automic.specifics.GoRunCommand.main(GoRunCommand.java:65)

There should not be the same count because the filter argument is another.

Thanks,
Harald

**Comment by brendanSapience** [comment]
interesting. The count returned is the same because the filtering occurs after retrieving the statistics. Which isnt optimal. I will implement a more efficient mechanism instead.

**Comment by brendanSapience** [comment]
@HaraldSchlager, i opened a corresponding issue here #19
