### ISSUE TITLE
TASKS_Operation u_prompts parameter -commit

### ISSUE THREAD

**Issue by HaraldSchlager** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#17]
hi brendan, today I was testing the new promptset possibilies and I am not sure if the behavior is the "designed" one: 

Step 1 was to start a job with a promptset inside. So the status was "waiting for input". Then
I can look with TASKS_Operations -u_showprompt what promptsets are there or use the 
TASKS_Operations -u_prompts to fill out the promptset. If I execute this "TASKS_Operations -u_prompts
... " without "-commit" it is also executing the job.

Sample:
--
-- Starting the Job
--
eg40app01v:/app/automic/tools/binutils> java -jar OBJECTS_Execute.jar -H localhost -P 58200 -name "USER1.TEST.JOB" -e_now -e_ldate 20161211-0955
--
-- Looking for a promptset
--
eg40app01v:/app/automic/tools/binutils> java -jar TASKS_Operations.jar -H localhost -P 58200 -f_name "USER1.TEST.JOB" -u_showprpt
%% => Simulation Mode - Nothing will be updated. [ Hint: Run commit option to update objects (-commit) ] <= %%

%% => [ USER1.TEST.JOB | JOBS | 0424 | <UNIX> | Unix | CLIENT_QUEUE | 1186419 | [0:00:00 :  00:00:00 -  00:00:00] | Waiting for user input | USER1.DEV.MAIN.EG.LOGIN | USER1/UC ]
         %% Promptset Found:USER1.PRPT
         %% [Variable Name | Variable Value]:  [ TEXTFIELD1# |  ]
--
-- Putting a value to the promptset variable
--
eg40app01v:/app/automic/tools/binutils> java -jar TASKS_Operations.jar -H localhost -P 58200 -f_name "USER1.TEST.JOB" -u_prompts "USER1.PRPT['TEXTFIELD1#':'HUGO']"
%% => Simulation Mode - Nothing will be updated. [ Hint: Run commit option to update objects (-commit) ] <= %%

%% => [ USER1.TEST.JOB | JOBS | 0424 | <UNIX> | Unix | CLIENT_QUEUE | 1186419 | [0:00:00 :  00:00:00 -  00:00:00] | Waiting for user input | USER1.DEV.MAIN.EG.LOGIN | USER1/UC ]
         %% Promptset Found:USER1.PRPT
         %% Update of PromptSet entry USER1.PRPT: [Variable Name | Variable Value]:  [ TEXTFIELD1# | HUGO ]
         %% Done!

Is there a general rule when "commit" is needed ?

Thanks,
Harald

**Comment by brendanSapience** [comment]
It's a bug. Not commit should definitely NOT submit the job.  will fix it. thank you!

**Comment by brendanSapience** [comment]
fixed!
