### ISSUE TITLE
OBJECTS_Execute.jar with a promptset and not Generated at runtime

### ISSUE THREAD

**Issue by HaraldSchlager** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#18]
hi brendan,

If OBJECTS_Execute.jar with a promptset and not Generated at runtime the binary does not finish.

Sample:
eg40app01v:/app/automic/tools/binutils> java -jar OBJECTS_Execute.jar -H localhost -P 58200 -name "USER1.TEST.JOB" -e_now -e_ldate 20161211-0955 -commit
%% => Object Marked for Execution: [ NOW |  | JOBS | USER1.TEST.JOB |  | 0424/DEVELOP/USER1/T ]

will be waiting for user input and does not finish. Maybe in this case the binary should finish with
a warning or similar but not wait at the command line ?

thanks,
harald

**Comment by brendanSapience** [comment]
ah yes, good point. I will add a check in it.

**Comment by brendanSapience** [comment]
Done!

the binary will wait a certain amount of time (timeout) before exiting, Default value: 10 seconds.

the timeout value can be changed with a new option: -e_timeout (in seconds).

**Comment by HaraldSchlager** [comment]
hi brendan, thanks I can see the timeout. cosmetic - maybe instead the word "Error" Info or Warning would be more exact because of RC=0.

eg40app01v:/app/automic/tools/egitutils> java -jar ../binutils/OBJECTS_Execute.jar -H localhost -P 58200 -name "USER1.TEST.JOB" -e_now -e_ldate 20161214-0819 -commit
 %% INFO: No Default Config File Found: ./connection.config
%% => Object Marked for Execution: [ NOW |  | JOBS | H504BSA.TEST.JOB |  | 0424/DEVELOP/USER1/T ]
         **_Error_**: Timeout Occured on execution for: USER1.TEST.JOB. Maybe a prompt is blocking the execution?
eg40app01v:/app/automic/tools/egitutils> echo $?
0

thanks,
harald

**Comment by brendanSapience** [comment]
makes sense. Changed to Warning now.
