### ISSUE TITLE
Filter in Statistics_List is too wide

### ISSUE THREAD

**Issue by brendanSapience** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#19]
filters are applied after retrieving all statistics.. which means it can never work for larger system.

the mechanism needs to apply filters before the statistics are retrieved.

**Comment by brendanSapience** [comment]
@HaraldSchlager, i released a new version of the STATISTICS_List.jar that has 1 additional option.

-fr_name (the R in FR is for request): it will apply a filter before the request to retrieve statistics is sent to the engine.

=> So far i only implemented one such filter for names (i will add more later)
=> I want to keep both -fr* filters and -f* filters because -fr* filters can only work with patterns "*" and "?" while -f* filters work with all regular expressions

ex:

`java -jar STATISTICS_List.jar -fr_name "*PSP*"`

**Comment by brendanSapience** [comment]
@HaraldSchlager, i redelivered a more advanced version of the binary with more fr_* filters.

fr_* filters are "request filters" and are applied BEFORE a request is sent to AE (large performance gain when used).

**Comment by HaraldSchlager** [comment]
hi brendan, thanks -fr_name and -fr_rand*  are working, so I see now the statistics.
br, harald
