### ISSUE TITLE
 VARA_STATIC_Update.jar - Missing filter on values and index

### ISSUE THREAD

**Issue by al1moa6** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#20]
Suggestion of enhancement to enable filtering on content of VARA STATIC Objects :

-f_spec <arg>       [OPTIONAL] ("['Key','Value 1','Value 2','Value 3','Value 4','Value 5']" (Regex Supported))  - Filter by values.

Should enable to filter on any of the value or index (keyword) field if a value is entered. 
Can be a Regex or No Regex filter for each field. 
If field non significant for filtering, use a '*' or empty field '' as value for it in the <arg>.

Could be extended to VARA SQL and VARA SQLI in filtering the preview result if technically possible. In that case No Regex on the global result field should be good for a first solution.

**Comment by brendanSapience** [comment]
it would  technically be possible, but it would have a significant impact on performance: each object would need to be physically opened in order to filter on key / value content.

it is already possible to do something similar using a 2 step process: 

1- use the name filter with -d_spec to show the content of each VARA
2- only select VARA that contain a particular pattern
3- update selected VARA

i will add it to the list of PEs.

Thank you!

**Comment by al1moa6** [comment]
Is this 3 step process faster than including an option to do it in one single action ? It means also opening all objects to do to show contents or is this done by an SQL statement ?

Concerning performance, maybe a warning that this takes time could be enough. People using this feature should be aware that it requires a lot of data loading anyway. The use of this type of function is more to enable a search and replace facility in the values using filter on those values, in one operation, rather than having to do scripting, loops, etc ... 

Bypass solution exists of course but nice to have ....

**Comment by brendanSapience** [comment]
Done.

you can use the new option -fd_row in order to filter on row content (key, or any of the values).

example:

` -name "VARA.TEST.*" -fd_row "['KEY1','.*','.*','.*','.*','.*']"`

` -name "VARA.TEST.*" -fd_row "['.*','Value 1','.*','.*','.*','.*']"`
