### ISSUE TITLE
OBJECTS_Duplicate can't duplicate USER Object type

### ISSUE THREAD

**Issue by al1moa6** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#21]
Trying to duplicate a USER Object and got an error in the management of the new name that contains a '/', that is an exception in the authorized characters for Object names. 

See attached file for details as the simulation is not detecting the problem, only in commit.
[Erreurs_001.txt](https://github.com/brendanSapience/UC4-Automic-AE-CLI-Binary-Repository/files/648516/Erreurs_001.txt)

Note : Maybe this could be the case also with 
Agent names that contains a '-' that is also an exception in authorized characters for Objects names.

**Comment by brendanSapience** [comment]
ah yeah, it was a known bug i meant to fix a while ago.

it's fixed now :) should work for Users and Hosts as well.
