### ISSUE TITLE
USER_Update  -> Error: Could not find or load main class com.automic.specifics.GoRunCommand 

### ISSUE THREAD

**Issue by HaraldSchlager** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#22]
hi brendan, in the new release from today,

eg40app01v:/app/automic/tools/egitutils> java -jar ../binutils/USER_Update.jar -help
Error: Could not find or load main class com.automic.specifics.GoRunCommand

Thanks,
Harald

**Comment by brendanSapience** [comment]
fixed.
