### ISSUE TITLE
OBJECTS_Create.jar cannot create JOB_WIN

### ISSUE THREAD

**Issue by laolau** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#24]
Hi Brendan,

It seems my commands doesn't work. I try to create a JOBS_WIN, but it failed. (successful for JOBS_UNIX)
I download last binairies (2016 12 14)

java -jar OBJECTS_Create.jar -name \"A\" -template \"JOBS_WIN\" -folder \"TEST_JAVA_API\"

Thanks

Laurent from Automic

**Comment by brendanSapience** [comment]
Hi Laurent,

there is a bug in one of the classes of the API it seems. I implemented a workaround, it should work now.
