### ISSUE TITLE
CLI Binary to list AE Object

### ISSUE THREAD

**Issue by laolau** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#32]
Hi ,

Can you create a binary to list AE Object ?

For example 
- list all agent for a Client
- list agent named W*
- list agent type WIN

Thanks a lot

**Comment by brendanSapience** [comment]
Done. 
![image](https://cloud.githubusercontent.com/assets/9252657/21905874/f62e83c4-d8d6-11e6-9314-de36ca702503.png)
