### ISSUE TITLE
In Schedule Object, show tasks properties

### ISSUE THREAD

**Issue by laolau** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#48]
Hi Brendan,

In the binairy JSCH_Update.jar, can you add the option to show task properties (starttime, variables, calendar, runtime)

Thanks

**Comment by brendanSapience** [comment]
Done, see commit #d3fecd7 

three more options available: 

-ds_tsk_cale_cal          [OPTIONAL - Specific Display for Tasks] - Display the Calendar Conditions in SCHED Tasks
 -ds_tsk_cale_res          [OPTIONAL - Specific Display for Tasks] - Display the Result Conditions in SCHED Tasks
 -ds_tsk_cale_var          [OPTIONAL - Specific Display for Tasks] - Display the Variable in SCHED Tasks
