### ISSUE TITLE
HOSTGROUPS_Update.jar -f_name option throwing error

### ISSUE THREAD

**Issue by djustins** [brendanSapience/UC4-Automic-AE-CLI-Binary-Repository#50]
I'm using AE v10.0.8, so i hope that's not the issue. 

No matter the specified HOSTG, either a straight name or a filter with wildcards, i'm getting the following error: 

(225)==> java -jar HOSTGROUPS_Update.jar -F connection.config -f_name "*"
%% => Simulation Mode - Nothing will be updated. [ Hint: Run commit option to update objects (-commit) ] <= %%

Error: A name may only include the following characters at its first position:
A-Z, 0-9, #, $, @, _ , -, . and <> for replacing and searching HOST objects.
Filtering Progress:

 %% No Hostgroup Matching Name * Were Found.

**Comment by brendanSapience** [comment]
Hi,

did you check the options for this CLI? you can use the "-h" option to retrieve available parameters, here is the ones you need:

 -f_name <arg>             [OPTIONAL] (RegEx supported) - Filter by Hostgroup Name.                   
 -name <arg>               [MANDATORY] ("*" and "?" supported) - Filter by Name.

this means you need to specify the -name option ("*" would be acceptable), and it also means you do not need -f_name (however, you can specify it as well for additional filtering.. -f_name takes Regular Expressions as indicated. your option "*" is not a valid regular expression as "*" is a meta character alone.

quick fix for you:

change -f_name "*" to -name "*" in your command, and it should work :)
